kind: pipeline
type: docker
name: docker_build_images

steps:
- name: ci_images_minimal
  image: plugins/docker
  settings:
    dockerfile: minimal.Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: housemap/ci-images
    tags: minimal

- name: ci_images_java
  image: plugins/docker
  settings:
    dockerfile: java.Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: housemap/ci-images
    tags: java

- name: ci_images_android
  image: plugins/docker
  settings:
    dockerfile: android.Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: housemap/ci-images
    tags: android


- name: ci_images_node
  image: plugins/docker
  settings:
    dockerfile: node.Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: housemap/ci-images
    tags: node
