kind: pipeline
type: docker
name: dind

steps:
- name: build
  image: docker:dind
  environment:
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
  volumes:
      - name: docker_sock
        path: /var/run/docker.sock
  commands:
  - DOCKER_USERNAME=$DOCKER_USERNAME DOCKER_PASSWORD=$DOCKER_PASSWORD sh build_deploy.sh
  when:
    branch:
    - master

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock

services:
  - name: docker
    image: docker:dind
    privileged: true
    command: [ --storage-driver=overlay2]